---
- name: HKEX RHEL Containment Main Entry Point
  hosts: all
  gather_facts: yes
  vars:
    # Extra variables from XSOAR frontend via AAP API
    action: "{{ action }}"              # 'containment' or 'resume'
    profile: "{{ profile | default('') }}"  # 'FULL', 'PARTIAL', 'REBUILT' (for containment)
#    inbound_whitelist: "{{ inbound_whitelist | default([]) }}"
    outbound_whitelist: "{{ outbound_whitelist | default([]) }}"
    # Default variables
    backup_path: "/var/backup/hkex"
    default_inbound_whitelist: []
    default_outbound_whitelist: []

  tasks:
    - name: Validate action variable
      fail:
        msg: "Action must be either 'containment' or 'resume'"
      when: action not in ['containment', 'resume']

    - name: Run containment role
      include_role:
        name: containment
      when: action == 'containment'

    - name: Run resume role
      include_role:
        name: resume
      when: action == 'resume'