---
- name: HKEX RHEL Containment Main Entry Point
  hosts: all
  gather_facts: yes
  vars:
    # Variables passed from XSOAR frontend via AAP API
    action: "{{ action }}"              # 'containment' or 'resume'
    profile: "{{ profile | default('') }}"  # 'FULL', 'PARTIAL', 'REBUILT' (for containment)
    inbound_whitelist: "{{ inbound_whitelist | default([]) }}"
    outbound_whitelist: "{{ outbound_whitelist | default([]) }}"

  tasks:
    - name: Validate action variable
      fail:
        msg: "Action must be either 'containment' or 'resume'"
      when: action not in ['containment', 'resume']

    - name: Include containment playbook for RHEL 7
      include_tasks: "hkex_rhel7_containment.yml"
      when: ansible_distribution_major_version == '7' and action == 'containment'

    - name: Include containment playbook for RHEL 8
      include_tasks: "hkex_rhel8_containment.yml"
      when: ansible_distribution_major_version == '8' and action == 'containment'

    - name: Include containment playbook for RHEL 9
      include_tasks: "hkex_rhel9_containment.yml"
      when: ansible_distribution_major_version == '9' and action == 'containment'

    - name: Include resume playbook for RHEL 7
      include_tasks: "hkex_rhel7_resume.yml"
      when: ansible_distribution_major_version == '7' and action == 'resume'

    - name: Include resume playbook for RHEL 8
      include_tasks: "hkex_rhel8_resume.yml"
      when: ansible_distribution_major_version == '8' and action == 'resume'

    - name: Include resume playbook for RHEL 9
      include_tasks: "hkex_rhel9_resume.yml"
      when: ansible_distribution_major_version == '9' and action == 'resume'
