---
- name: Include RHEL 7 resume tasks
  include_tasks: rhel7_resume.yml
  when: ansible_distribution_major_version == '7'

- name: Include RHEL 8 resume tasks
  include_tasks: rhel8_resume.yml
  when: ansible_distribution_major_version == '8'

- name: Include RHEL 9 resume tasks
  include_tasks: rhel9_resume.yml
  when: ansible_distribution_major_version == '9'