---
- name: Create backup directory
  become: yes
  file:
    path: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}"
    state: directory
    mode: '0700'

- name: Check if nftables backup exists
  become: yes
  stat:
    path: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}/nftables.conf"
  register: backup_check
  failed_when: backup_check.stat.exists

- name: Backup existing nftables configuration
  become: yes
  copy:
    src: "/etc/nftables.conf"
    dest: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}/nftables.conf"
    remote_src: yes

- name: Generate nftables configuration
  become: yes
  template:
    src: "nftables/{{ profile | lower }}.j2"
    dest: "/etc/nftables.conf"
    mode: '0600'

- name: Apply nftables rules
  become: yes
  service:
    name: nftables
    state: restarted
  register: nftables_result

- name: Verify nftables rules
  become: yes
  shell: nft list ruleset
  register: nftables_verify
  changed_when: false

- name: Fallback on failure
  become: yes
  block:
    - name: Restore nftables from backup
      copy:
        src: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}/nftables.conf"
        dest: "/etc/nftables.conf"
        remote_src: yes

    - name: Restart nftables after restore
      service:
        name: nftables
        state: restarted

    - name: Remove backup on failure
      file:
        path: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}"
        state: absent
  when: nftables_result.failed